name: Email Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  email_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python report.py

      - name: Email report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Daily Report
          body: |
            Hi,

            Please find attached the daily report.

          attachments: |
            /path/to/report.txt
